name: adaptive_ui
description: Platforma göre otomatik olarak Cupertino veya Material widget kullanan Flutter UI bileşenleri.
version: 0.1.2
homepage: https://github.com/zeynepgokdogan/adaptive_ui

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
